### PR TITLE
more attempt to fix 151

### PR DESCRIPTION
**Pull request by i-make-robots**
@Jackymancs4 does this help at all?  I think the problem is related to vertex array object (VAOs).

### CODE REVIEW

**Comment by Jackymancs4** [comment]
I'm afraid not.

- Test 0: all grey
- Test 1: color triangle
- Test 2: color triangle
- Test 3: whatever was shown before, renderer becomes unresponsive.
- Test 4: whatever was shown before, renderer becomes unresponsive.
- Test 5: whatever was shown before, renderer becomes unresponsive.

**Comment by i-make-robots** [comment]
Wait, what?  Did test 3 work before this PR?

**Comment by Jackymancs4** [comment]
With master:
- Test 0: all black
- Test 1: all black
- Test 2: color triangle, renderer becomes unresponsive.
- Test 3: all black (or unresponsive)
- Test 4: all black (or unresponsive)
- Test 5: all black (or unresponsive)

**Comment by Jackymancs4** [comment]
> I'm afraid not. 

I was wrong. A clean build actually fixed it.
- Test 0: all grey
- Test 1: color triangle
- Test 2: color triangle
- Test 3: color triangle
- Test 4: Changing background color
- Test 5: small rotating triangle

**Comment by i-make-robots** [comment]
Huzzah!  Does that mean a clean build of Robot Overlord works?!

**Comment by Jackymancs4** [comment]
Nope, tried that. But I also did a bisect, and whatever you did in "more attempt to fix 151" (70db3cfd94acc6fbf42f3d0404ac235a1560558f) made all the difference for for OpenGLTestOrthographic.

Running RobotOverlord on that commit still gets me black background.

**Comment by i-make-robots** [comment]
What about `OpenGLTestPerspective`?

**Comment by Jackymancs4** [comment]
Once again, my fault. On https://github.com/MarginallyClever/Robot-Overlord-App/commit/70db3cfd94acc6fbf42f3d0404ac235a1560558f everything works, both and OpenGLTestPerspective and RobotOverlord (congrats!). 

On 7c23a1b3d43e705034f7ba60206df7eb895d9a69 RobotOverlord has the black background issue,  and tests from 2 to 5 don't pass.

**Comment by i-make-robots** [comment]
Huh.  the change in 7c23a1b is technically more correct...

**Comment by Jackymancs4** [comment]
This time I'm confident in my assesment, as reverting https://github.com/MarginallyClever/Robot-Overlord-App/commit/7c23a1b3d43e705034f7ba60206df7eb895d9a69 fixes both tests and main app.

**Comment by Jackymancs4** [comment]
> Huh. the change in https://github.com/MarginallyClever/Robot-Overlord-App/commit/7c23a1b3d43e705034f7ba60206df7eb895d9a69 is technically more correct...

Do you really need to unbind the VAOs?
E.g. https://stackoverflow.com/questions/25412767/opengl-glbindbuffer0-outside-vao

Because commenting https://github.com/MarginallyClever/Robot-Overlord-App/blob/f9fb5396caf675a78a05f3325ebf56d2acbfaac0/src/main/java/com/marginallyclever/robotoverlord/systems/render/mesh/Mesh.java#L186 and https://github.com/MarginallyClever/Robot-Overlord-App/blob/f9fb5396caf675a78a05f3325ebf56d2acbfaac0/src/main/java/com/marginallyclever/robotoverlord/renderpanel/OpenGLTestOrthographic.java#L166 seems to fix my problem.

**Comment by i-make-robots** [comment]
in Compass3d, `cube.getModel().setDirty(true);`  needs to be called before `cube.render();` or the cube disappears after a preferences change.  I don't know why this happens, it shouldn't disappear.  it gets completely rebuilt when the OpenglRenderPanel is created.

**Comment by Jackymancs4** [comment]
I confirm that building on the last commit fixes the issues with the renderer. 
I suggest merging as this closes #151 now.

**Comment by Jackymancs4** [comment]
Last commit fixes #167

**Comment by i-make-robots** [comment]
If that's the case then we can consider #151 and #167 closed.

**Pull request merged**
